name: almanada_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  get: ^4.6.6
  get_it: ^7.2.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.0.18
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.9.1
  get_storage: ^2.1.1
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  bloc: ^8.1.1
  flutter_local_notifications: ^17.2.2
  flutter_bloc: ^8.1.2
  devicelocale: ^0.6.0
  carousel_slider_plus: ^7.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  google_maps_flutter: ^2.9.0
  fan_carousel_image_slider: ^1.0.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

  
  flutter_lints: ^3.0.0



flutter:
  assets:
    - assets/images/
    - assets/icons/
    - lang/ar.json
    - lang/en.json
    
  uses-material-design: true

  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
