// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZklF0HXEcdSiiVfdjqNMZ5jw-S1vfbE',
    appId: '1:470751147840:web:08a51c0c1911f7ccb6aca5',
    messagingSenderId: '470751147840',
    projectId: 'almanada-49c1c',
    authDomain: 'almanada-49c1c.firebaseapp.com',
    storageBucket: 'almanada-49c1c.appspot.com',
    measurementId: 'G-SLRHKGT6R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfMHI1Y8ssOPPs3bMNhJzxeJ9QwCcLlUk',
    appId: '1:470751147840:android:c9f9c7d806ee5107b6aca5',
    messagingSenderId: '470751147840',
    projectId: 'almanada-49c1c',
    storageBucket: 'almanada-49c1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ByX7PaNcZdBA7CHh8TT4omI91LjcZTE',
    appId: '1:470751147840:ios:c8e77c372cb4d02fb6aca5',
    messagingSenderId: '470751147840',
    projectId: 'almanada-49c1c',
    storageBucket: 'almanada-49c1c.appspot.com',
    iosBundleId: 'com.example.almanadaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ByX7PaNcZdBA7CHh8TT4omI91LjcZTE',
    appId: '1:470751147840:ios:c8e77c372cb4d02fb6aca5',
    messagingSenderId: '470751147840',
    projectId: 'almanada-49c1c',
    storageBucket: 'almanada-49c1c.appspot.com',
    iosBundleId: 'com.example.almanadaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtZklF0HXEcdSiiVfdjqNMZ5jw-S1vfbE',
    appId: '1:470751147840:web:bcada7ba98dafe84b6aca5',
    messagingSenderId: '470751147840',
    projectId: 'almanada-49c1c',
    authDomain: 'almanada-49c1c.firebaseapp.com',
    storageBucket: 'almanada-49c1c.appspot.com',
    measurementId: 'G-E00DBR5QC5',
  );
}
